# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-11-02 15:39
from __future__ import unicode_literals

from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    for model_name in ('buildrecord', 'externaldependency', 'githubrepository', 'packagesource', 'repository', 'series'):
        m = apps.get_model('buildsvc', model_name)
        for row in m.objects.all():
            row.uuid = uuid.uuid4()
            row.save()


class Migration(migrations.Migration):

    dependencies = [
        ('buildsvc', '0012_add_uuid_field'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
