# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 20:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildsvc', '0019_import_key_data'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='githubrepository',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='githubrepository',
            name='user',
        ),
        migrations.DeleteModel(
            name='GithubRepository',
        ),
    ]
