# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 19:15
from __future__ import unicode_literals

from django.db import migrations


def add_internal_repository_driver_feature(apps, schema_editor):
    Feature = apps.get_model("common", "Feature")
    Feature.objects.create(name='BUILDSVC_INTERNAL_REPOSITORY_DRIVER', on_by_default=False, description='Use experimental internal repository generator.')


def remove_internal_repository_driver_feature(apps, schema_editor):
    Feature = apps.get_model("common", "Feature")
    Feature.objects.filter(name='BUILDSVC_INTERNAL_REPOSITORY_DRIVER').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('buildsvc', '0023_auto_20160128_1603'),
    ]

    operations = [
        migrations.RunPython(add_internal_repository_driver_feature,
                             remove_internal_repository_driver_feature)
    ]
