# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-08 09:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildsvc', '0025_proper_repo_management'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BuildRecord',
            new_name='Build',
        ),
    ]
