# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='json',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
