# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-11-03 07:46
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mirrorsvc', '0009_mirrorset_extra_admins'),
    ]

    operations = [
        migrations.AddField(
            model_name='mirror',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='mirrorset',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
